/* Generated By:JavaCC: Do not edit this line. SimpleCalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NUMBER = 1;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<NUMBER>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"x\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
  };

}
